name: m1-yaml

on: pull_request

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: [self-hosted, macOS, ARM]
    strategy:
      matrix:
       include:
          - rust: nightly-2021-07-21
          - rust: nightly
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          profile: minimal
      - run: |
          pwd
          ls
          cargo build --release
